title: "Yaser Sellami's Portfolio"
description: "Machine Learning projects"
theme: jekyll-theme-minimal

sass:
  style: compressed

navigation:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects
  - title: "Contacts"
    url: /contact


